---

title: Default

blocks:

  - title: FC Packets
    type: metric
    placement: [1,1]
    size: [3,2]
    contents:

      - title: Time since last FC packet
        data: "d.server.time - d.FC.TimeLastPacketReceived"
        format: "%7.1f"
        units: seconds
        importance: minor
        viz: none

      - title: Dropped FC packets
        format: "%5d"
        data: "d.FC.PacketsLostRecently"
        importance: major
        viz: none

      - title: Packet Rate
        format: "%6.1f"
        data: "d.FC.PacketsReceivedRecently / 0.1"
        units: packets/second
        importance: major
        viz: sparkline
        scale: [100.0,0.0]


  - title: IMU
    type: metric
    placement: [1,3]
    size: [1,1]
    contents:

      - title: Accel
        data: "-d.FC.ADIS.Acc_X_mean"
        format: "%5.1f"
        units: m/s/s
        importance: minor
        viz: none

      - title: Roll
        data: "d.FC.ADIS.Gyro_X_mean"
        format: "%5.1f"
        units: m/s/s
        importance: minor
        viz: none


  - title: ROLL
    type: metric
    placement: [2,3]
    size: [3,1]
    contents:

      - title: Fin Angle
        data: "d.ROLL.Angle"
        format: "%5.1f"
        units: degrees
        importance: major
        viz: sparkline
        range: [100.0,-100.0]


  - title: GPS
    type: metric
    placement: [5,1]
    size: [2,2]
    contents:

      - title: Nav Mode
        data: "d.FC.GPS1.Nav_Mode"
        format: "%4d"
        importance: minor
        viz: none

      - title: Number of Sats
        data: "d.FC.GPS1.Num_Of_Sats"
        format: "%4d"
        importance: major
        viz: none

      - title: Latitude
        data: "d.FC.GPS1.Latitude"
        format: "%16.10f"
        importance: minor
        viz: none

      - title: Longitude
        data: "d.FC.GPS1.Longitude"
        format: "%16.10f"
        importance: minor
        viz: none

      - title: Height
        data: "d.FC.GPS1.Height"
        units: meters
        format: "%4.0f"
        importance: minor
        viz: sparkline
        scale: [5000.0,500.0]
        showzero: True

      - title: Speed go up
        data: "d.FC.GPS1.VUp"
        units: m/s
        format: "%4.1f"
        importance: minor
        viz: sparkline
        scale: [400.0,-100.0]
        showzero: True

...
