---

title: Default

blocks:

  - title: FC Packets
    type: metric
    placement: [1,1]
    size: [2,2]
    contents:

      - title: Time since last FC packet
        data: "d.server.time - d.FC.TimeLastPacketReceived"
        format: "%7.1f"
        units: seconds
        importance: major
        viz: none

      - title: Dropped FC packets
        format: "%5d"
        data: "d.FC.PacketsLostRecently"
        importance: minor
        viz: none

      - title: Packet Rate
        format: "%6.1f"
        data: "d.FC.PacketsReceivedRecently / 0.1"
        units: packets/second
        importance: minor
        viz: sparkline

...
