---
# All possible units and unit conversions are outlined in scripts/quantities.js
# Adding the suffix .Max or .Min to any JSON source will give you the maximum or minimum value over time.
# Adding the suffix .Neg to any JSON source will negate the incoming value.

  - id: Adis Layout
    type: Layout
    columns:
      - id: column1
        width: 25%
      - id: column2
        width: 75%

  - id: Stats
    type: Text
    height: 125
    column: column1
    controls:
      - label: Incoming Packets
        source: Stats.PacketsReceivedRecently
      - label: Incoming Total
        source: Stats.PacketsReceivedTotal
      - label: Lost Total
        source: Stats.PacketsLostTotal
      - label: Last Packet Rcvd
        source: Stats.TimeLastPacketReceived
        
  - id: Acceleration
    type: Text
    height: 125
    column: column1
    controls:
      - label: X
        source: ADIS.Acc_X_mean
        units: m/s^2
      - label: Y
        source: ADIS.Acc_Y_mean
        units: m/s^2
      - label: Z
        source: ADIS.Acc_Z_mean
        units: m/s^2

  - id: Gyroscrope
    type: Text
    height: 125
    column: column1
    controls:
      - label: X
        source: ADIS.Gyro_X_mean
        units: deg/sec
      - label: Y
        source: ADIS.Gyro_Y_mean
        units: deg/sec
      - label: Z
        source: ADIS.Gyro_Z_mean
        units: deg/sec
        
  - id: Magnetometer
    type: Text
    height: 125
    column: column1
    controls:
      - label: X
        source: ADIS.Magn_X_mean
        units: T
      - label: Y
        source: ADIS.Magn_Y_mean
        units: T
      - label: Z
        source: ADIS.Magn_Z_mean
        units: T

  - id: Z-Roll
    type: LineGraph
    width: 600
    height: 330
    column: column2
    maxDataSize: 200
    controls:
      - label: X 
        source: ADIS.Acc_X_mean
        units: m/s^2
      - label: Y
        source: ADIS.Acc_Y_mean
        units: m/s^2
      - label: Z
        source: ADIS.Acc_Z_mean
        units: m/s^2



  - id: Temp/VCC
    type: Text
    height: 125
    column: column2
    controls:
      - label: Temperature
        source: ADIS.Temp_mean
        units: tempC
      - label: VCC
        source: ADIS.VCC_mean
        units: V
