
---
# All possible units and unit conversions are outlined in scripts/quantities.js
# Adding the suffix .Max or .Min to any JSON source will give you the maximum or minimum value over time.
# Adding the suffix .Neg to any JSON source will negate the incoming value.

  - type: Layout
    columns:
      - id: column1
        width: 25%
      - id: column2
        width: 75%
        columns:
          - id: column2_a
            width: 100%
          - id: column2_b
            width: 50%
          - id: column2_c
            width: 50%

  - id: Packet Stats
    type: Text
    height: 125
    column: column1
    controls:
      - label: Incoming Packets
        source: Stats.PacketsReceivedRecently
      - label: Incoming Total
        source: Stats.PacketsReceivedTotal
      - label: Lost Total
        source: Stats.PacketsLostTotal
      - label: Last Packet Rcvd
        source: Stats.TimeLastPacketReceived
        units: s
      - label: Time
        source: Stats.MostRecentTimestamp
      - label: Rate
        source: Stats.PacketRate
        units: packet/s
      - label: Drop Rate
        source: Stats.DropRate
        units: percent
      - label: Current Sequence Number
        source: Stats.CurrentSeqn


  - id: GPS Status
    type: Text
    height: 125
    column: column1
    controls:
      - label: NavMode
        source: GPS1.NavMode
      - label: Satellites
        source: GPS1.NumOfSats

  - id: GPS
    type: Text
    height: 125
    column: column1
    controls:
      - label: Lat
        source: GPS1.Latitude
        units: deg
      - label: Long
        source: GPS1.Longitude
        units: deg
      - label: Height
        source: GPS1.Height
        units: m
      - label: Max Height
        source: GPS1.Height.Max
        units: m

  - id: Acceleration
    type: Text
    height: 125
    column: column1
    controls:
      - label: X
        source: ADIS.Acc_X_mean
        units: m/s^2
      - label: Y
        source: ADIS.Acc_Y_mean
        units: m/s^2
      - label: Z
        source: ADIS.Acc_Z_mean
        units: m/s^2

        
  - id: Up_Accel
    type: LineGraph
    width: 600
    height: 320
    column: column2_a
    maxDataSize: 100
    controls:
      - label: Up Accel
        source: ADIS.Acc_X_mean
        units: m/s^2

  - id: Gyroscrope
    type: Text
    height: 125
    column: column2_c
    controls:
      - label: X
        source: ADIS.Gyro_X_mean
        units: deg/sec
      - label: Y
        source: ADIS.Gyro_Y_mean
        units: deg/sec
      - label: Z
        source: ADIS.Gyro_Z_mean
        units: deg/sec
        
