---

  - type: Layout
    columns:
      - id: Column_1
        width: 100%
        columns:
          - id: Column_3
            width: 25%
          - id: Column_4
            width: 75%

  - id: Packet Stats
    type: Text
    height: 230
    column: Column_3
    controls:
      - label: Incoming Packets
        source: Stats.PacketsReceivedRecently
      - label: Incoming Total
        source: Stats.PacketsReceivedTotal
      - label: Lost Total
        source: Stats.PacketsLostTotal
      - label: Last Packet Rcvd
        source: Stats.TimeLastPacketReceived
        units: s
      - label: Time
        source: Stats.MostRecentTimestamp
      - label: Rate
        source: Stats.PacketRate
        units: packet/s
      - label: Drop Rate
        source: Stats.DropRate
        units: percent
      - label: Current Sequence Number
        source: Stats.CurrentSeqn


  - id: Packets
    type: LineGraph
    width: 1100
    height: 190
    column: Column_4
    maxDataSize: Number.MAX_VALUE
    controls:
      - label: Packet Rate
        source: Stats.PacketRate
        units: packet/s
      - label: Loss
        source: Stats.DropRate
        units: '%'
